### ISSUE TITLE
[PE-D][Tester B] Out of bounds error message wrong

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-T14-1/tp#147] opened 2024-04-05 19:41 UTC
![Screenshot 2024-04-05 at 4.57.43 PM.png](https://raw.githubusercontent.com/SimHanKiong/ped/main/files/57b3beb2-b6e5-4813-ab93-ce38985b6d57.png)

Error message for out of bounds index is different for 10 and 999999999

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: SimHanKiong/ped#15

**Comment by laybach** [comment] 2024-04-13 07:47
<img width="284" alt="image" src="https://github.com/AY2324S2-CS2103T-T14-1/tp/assets/38790326/324e96cf-4bd3-4ed6-910b-3599f4672945">
<img width="284" alt="image" src="https://github.com/AY2324S2-CS2103T-T14-1/tp/assets/38790326/03e53f7a-f8ce-4d8b-8121-72928a56a970">
There is no difference for values of 10 and 999999999
Closed as it is not a bug.

**Closed as completed by laybach** 2024-04-13 07:47 UTC
Labels: ab3_inherit
